apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: asia.gcr.io/inlaid-water-323109/my-app:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
