apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: my-web-server
        image: gcr.io/prime-force-325303/my-web-server
        ports:
        - containerPort: 80
        resources:
          requests:
                  cpu: "100m""
